---
dummy: 'Not having this file screws up `vagrant global-status`.'
dummy2: 'Just have to define enough keys fo the Vagrantfile to load successfully.'
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: 'dummy-entry'
        memory: '128'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: '0.0.0.0'
            forwarded_port: { }
        post_up_message: ''
        provider:
            virtualbox:
              modifyvm: { }
            vmware: { }
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options: { }
        synced_folder: { }
        usable_port_range:
            start: 10200
            stop: 10500
    ssh: { }
    vagrant: { }
