#!/usr/bin/env bash
################################################################################
#
# Custom redirector to point to composer-installed `cake`
#
################################################################################

Vendor/pear-pear.cakephp.org/CakePHP/bin/cake "$@"
exit